# Site settings
title: "Mind the Robot"
email: jean.uchoa@gmail.com
description: "my tech dump"
baseurl: ""
url: "http://roadhouse.github.io"
title_description: "My personal blog about tech stuff and related sutff"
title_image: "http://c7.staticflickr.com/1/38/96449422_ad9f5e82db_z.jpg"
google_analytics: "UA-78248583-1"
disqus_account: roadhousegithubio
github_repository: https://github.com/roadhouse/roadhouse.github.io
addthis_id: ra-57448e92bb684729
post_limit: 5

# Social usernames/URLs
twitter_username: roudi
github_username: roadhouse
linkedin_link: https://www.linkedin.com/in/jeanuchoa

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
